export const vnpStatus ={
  0: { vn: "Lưu nháp", cn: "儲存草稿" },
  1: { vn: "Đã tạo", cn: "已開單" },
  2: { vn: "Chuyển tin cho bưu tá", cn: "發送訊息中" },
  3: { vn: "Đang xử lý", cn: "正在處理" },
  4: { vn: "Đang lấy hàng", cn: "正在收件" },
  5: { vn: "Lấy hàng không thành công", cn: "收件末成功" },
  6: { vn: "Lấy hàng thành công", cn: "收件成功" },
  7: { vn: "Bưu cục đã nhận hàng", cn: "網點已收件成功" },
  8: { vn: "Lấy hàng thất bại", cn: "收件末成功" },
  9: { vn: "Hủy thu gom", cn: "取消收件" },
  10: { vn: "Đang vận chuyển", cn: "正在出貨" },
  11: { vn: "Đã đến Bưu cục phát", cn: "已到達派件網點" },
  12: { vn: "Đang giao hàng", cn: "正在派送" },
  13: { vn: "Chuyển tiếp", cn: "轉發" },
  14: { vn: "Đã giao hàng", cn: "已簽收" },
  15: { vn: "Giao hàng không thành công", cn: "派送末成功" },
  16: { vn: "Chờ để chuyển hoàn", cn: "退件" },
  17: { vn: "Đã duyệt hoàn", cn: "退件" },
  18: { vn: "Bắt đầu chuyển hoàn", cn: "退件" },
  19: { vn: "Hoàn thành công", cn: "退件成功" },
  20: { vn: "Đã trả hàng 1 phần", cn: "" },
  21: { vn: "Đã trả tiền COD", cn: "已付COD" },
  22: { vn: "Hủy giao hàng", cn: "取消派件" },
};